// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Stock struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	Quantity         int32
	ReservedQuantity int32
	Version          int32
	CreateDate       time.Time
	LastUpdateDate   time.Time
}

type StockReservation struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	OrderNumber uuid.UUID
	Quantity    int32
	CreateDate  time.Time
	CancelDate  *time.Time
}
