// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Stock struct {
	ID               uuid.UUID
	ProductID        uuid.UUID
	Quantity         int32
	ReservedQuantity int32
	Version          int32
	CreateDate       pgtype.Timestamp
	LastUpdateDate   pgtype.Timestamp
}

type StockReservation struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	OrderNumber uuid.UUID
	Quantity    int32
	CreateDate  pgtype.Timestamp
	CancelDate  pgtype.Timestamp
}
