// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddStockReservation(ctx context.Context, arg AddStockReservationParams) error
	CancelStockReservation(ctx context.Context, arg CancelStockReservationParams) error
	GetStock(ctx context.Context, productid uuid.UUID) (GetStockRow, error)
	GetStockReservations(ctx context.Context, ordernumber uuid.UUID) ([]StockReservation, error)
	GetStocks(ctx context.Context, arg GetStocksParams) ([]Stock, error)
	Insert(ctx context.Context, arg InsertParams) error
	StockReservationExists(ctx context.Context, ordernumber uuid.UUID) (bool, error)
	UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) error
	UpdateStockReserve(ctx context.Context, arg UpdateStockReserveParams) error
}

var _ Querier = (*Queries)(nil)
